language: python
python:
  - "2.7"
sudo: required
install:
  - git submodule update
  - cd x11-hash && python setup.py install && cd ..
  - pip install -I coverage twisted service_identity
script:
  - python run_p2pool.py --help
